api/urls.py
from django.urls import path, include

from rest_framework import routers

from  .views import TodoViewsets

r = routers.DefaultRouter()
r.register('todo',TodoViewsets)

urlpatterns = [
    path('', include(r.urls)),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as  auth_views
from users.views import register
from django.conf import settings
from django.conf.urls.static import static

from .views import root

urlpatterns = [
    path('', root,name='root'),
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('api/', include('api.urls')),

    path('login/', auth_views.LoginView.as_view(),name='login'),
    path('logout/', auth_views.LogoutView.as_view(),name='logout'),

    path('register/',register,name='register'),

    path('password-reset/',auth_views.PasswordResetView.as_view(
        template_name='users/password_reset.html',
        subject_template_name='users/password_reset_subject.txt',
        email_template_name='users/password_reset_email.html',
        html_email_template_name='users/password_reset_html_email.html',
        success_url='/todo/'),
        name='password-reset'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        post_reset_login=True,
        success_url='/todo/'
    ),name='password_reset_confirm'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . import views as v

app_name = 'todo'
urlpatterns = [
    path('', v.index, name='index'),
    path('new/', v.new, name='new'),
    path('<int:pk>/', v.show, name='show'),
    path('edit/<int:pk>/', v.edit, name='edit'),
    path('delete/<int:pk>/', v.delete, name='delete'),
]

todo/models.py
import os
import time

from django.db import models
from django.contrib.auth.models import User


def todo_attach_path(instance, filename):
    return os.path.join('todo', str(time.time()), filename)

class Tag(models.Model):
    title = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.title


class Todo(models.Model):
    title = models.CharField('標題', max_length=255)
    content = models.TextField('內容', max_length=500)
    status = models.BooleanField('已完成', default=False)
    tags = models.ManyToManyField(Tag, verbose_name='標籤')  # 多對多
    creator = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='建立者')  # 一對多
    attach = models.FileField('附件',blank=True, upload_to=todo_attach_path)

    def __str__(self):
        return self.title

users/models.py
from django.db import models

# Create your models here.

todo/forms.py
from django.forms import ModelForm,Form,BooleanField

from .models import Todo


class TodoModelForm(ModelForm):
    class Meta:
        model = Todo
        exclude = ['creator']

    def save(self, user, commit=True):
        todo = super().save(commit=False)
        todo.creator = user
        todo.save()

        self.save_m2m()

        return todo

class DeleteConfirmForm(Form):
    check = BooleanField(label = '你確定要刪除嗎？')

api/views.py
from rest_framework import viewsets

from todo.models import Todo

from .serializers import TodoSerializer

class TodoViewsets(viewsets.ModelViewSet):
    queryset = Todo.objects.all()
    serializer_class = TodoSerializer

core/views.py
from django.shortcuts import redirect



def root(request):
    return redirect('todo:index')

todo/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Todo
from .forms import TodoModelForm, DeleteConfirmForm
from django.contrib.auth.decorators import login_required


def index(request):
    todos = Todo.objects.all()
    return render(request, 'todo/index.html', {'todos': todos})


def show(request, pk):
    # post = Post.objects.get(pk=pk)
    todo = get_object_or_404(Todo, pk=pk)
    return render(request, 'todo/show.html', {
        'todo': todo
    })


@login_required
def new(request):
    form = TodoModelForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        todo = form.save(request.user)
        return redirect('todo:index')

    return render(request, 'todo/new.html', {'form': form})


@login_required
def edit(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    form = TodoModelForm(request.POST or None, request.FILES or None, instance=todo)
    if form.is_valid():
        todo = form.save(request.user)
        return redirect('todo:index')
    return render(request, 'todo/edit.html', {
        'form': form
    })


@login_required
def delete(request, pk):  # 非正統

    form = DeleteConfirmForm(request.POST or None)
    if form.is_valid() and form.cleaned_data['check']:
        todo = get_object_or_404(Todo, pk=pk)
        todo.delete()
        return redirect('todo:index')

    return render(request, 'todo/delete.html', {'form': form})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        login(request,user)
        return redirect('todo:index')

    return render(request,'users/register.html',{'form':form})

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta>
    {% block title %}

    {% endblock %}


    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>
<body>
<div class="container">
    {% if user.is_authenticated %}
        Hello {{ request.user.username }}
        <a href="{% url 'logout' %}" class="btn btn-primary">登出</a>
    {% else %}
        <a href="{% url 'login' %}" class="btn btn-primary">登入</a>
    {% endif %}

    {% block body %}

    {% endblock %}
</div>


</body>
</html>

templates/todo/delete.html
{% extends 'layout.html' %}

{% load bootstrap4 %}

{% block title %}
<title>Delete Todo</title>
{% endblock %}


{% block body %}
    <div class="row">
        <div class="col">
        <h1>Delete Todo</h1>
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

templates/todo/edit.html
{% extends 'layout.html' %}

{% load bootstrap4 %}

{% block title %}
<title>Edit Todo</title>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col">
        <h1>Edit Todo</h1>
            <form action="" method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

templates/todo/index.html
{% extends 'layout.html' %}

{% load bootstrap4 %}
{% block body %}

    <div class="row">
    <div class="col">
    {% if user.is_authenticated %}
        <a class="btn btn-outline-primary btn-sm float-right mt-3" href="{% url 'todo:new' %}">New Todo</a>
    {% endif %}


    <h1> TODO list</h1>
     <hr>
    <div class="list-group">
       {% for todo in todos %}
            <a href="{% url 'todo:show' todo.id %}" class="list-group-item list-group-item-action">{{ todo.title }}</a>
           {% empty %}
           <a href="#" class="list-group-item list-group-item-action disabled">No Todo!!!</a>
       {% endfor %}
    </div>
    </div>
    </div>


{% endblock %}

templates/todo/new.html
{% extends 'layout.html' %}

{% load bootstrap4 %}

{% block title %}
<title>New Todo</title>
{% endblock %}


{% block body %}
    <div class="row">
        <div class="col">
        <h1>New Todo</h1>
            <form action="" method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

templates/todo/show.html
{% extends "layout.html" %}

{#{% block title %}#}
{#show#}
{#{% endblock %}#}
{% load bootstrap4 %}

{% block body %}

    <h1>Posts</h1>
    {# 註解 #}
    <div>編號:{{todo.id}}</div>
    <h5>主題:{{todo.title}}</h5>
    <p>Tag:{{todo.tags.all | join:', ' }}</p>
    <p>內容:{{todo.content}}</p>

    {{ todo.title }}-{{ todo.content }} <br>
    <hr>
    {% if user.is_authenticated %}
        <a class="btn btn-outline-primary " href="{% url 'todo:edit' todo.id %}">Edit</a>
        <a class="btn btn-outline-primary " href="{% url 'todo:delete' todo.id %}">Delete</a>
        <a class="btn btn-outline-primary " href="{% url 'todo:index' %}">Back To List</a>
    {% else %}
        <a class="btn btn-outline-primary " href="{% url 'todo:index' %}">Back To List</a>
    {% endif %}


{% endblock %}

templates/users/password_reset.html
{% extends 'layout.html' %}

{% load bootstrap4 %}

{% block title %}
<title>password-reset</title>
{% endblock %}


{% block body %}
    <div class="row">
        <div class="col">
        <h1>password-reset</h1>
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

templates/users/password_reset_confirm.html
{% extends 'layout.html' %}

{% load bootstrap4 %}

{% block title %}
<title>password-reset</title>
{% endblock %}


{% block body %}
    <div class="row">
        <div class="col">
        <h1>password-reset</h1>

        {% if validlink %}
             <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        submit
                    </button>
                {% endbuttons %}
            </form>
        {% else %}
            <p>Link not valid</p>
        {% endif %}

        </div>
    </div>
{% endblock %}

templates/users/password_reset_email.html
有人要求重設 {{ email }} 的密碼
點選這個<a href="{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}"></a>連結：
來重設密碼
如果您沒有要求，請無視這封信。

templates/users/password_reset_html_email.html
有人要求重設 {{ email }} 的密碼
點選這個<a href="{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}">連結：</a>
來重設密碼
如果您沒有要求，請無視這封信。

templates/users/register.html
{% extends 'layout.html' %}

{% load bootstrap4 %}

{% block title %}
<title>Login</title>
{% endblock %}


{% block body %}
    <div class="row">
        <div class="col">
        <h1>Register</h1>
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                <a href="{% url 'login' %}">Already have a account?</a>
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        註冊
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}